# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b764ec7fb097e6839ba071dec5d2243228b0d7aef84704cc739bc46185bd28723175920d05ad1876b05dc17ec1620d3cd0544c6edef0549099836ac4c79d2f61

test:
  secret_key_base: b68f7b63570dfb6e487e883e25d76d0b715461144571c36c738d0dd7dfed132dc5d6602fea689cfbd2fe0fa09f0e87eb77556b8e4aefabd092fe3960bf0db626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
